build:
	# g++ -Wall -Wextra ./src/main.cpp ./src/ply.cpp ./src/entity.cpp -I/Library/Frameworks/GLUI.framework/Headers/ -framework OpenGL -framework GLUT -lglui -Wno-deprecated -o lab02
	g++ -Wall -Wextra ./src/algebraTest.cpp ./src/ply.cpp ./src/entity.cpp -I/Library/Frameworks/GLUI.framework/Headers/ -framework OpenGL -framework GLUT -lglui -Wno-deprecated -o algTest
