build:
	# g++ -Wall -Wextra Mobius.cpp Sphere.cpp Cylinder.cpp Cube.cpp Cone.cpp Circle.cpp Assignment1.cpp \
	# -I/Library/Frameworks/GLUI.framework/Headers/ -framework OpenGL -framework GLUT -lglui -Wno-deprecated -o Assignment1


	g++ -Wall -Wextra \
		./*.cpp  ./entities/*.cpp\
		-I/Library/Frameworks/GLUI.framework/Headers/ \
		-framework OpenGL \
		-framework GLUT -lglui -Wno-deprecated \
		-o hw3

