build:
	g++ -Wall -Wextra ./src/entity.cpp ./src/ply.cpp ./src/movieCamera.cpp ./src/main.cpp -I/Library/Frameworks/GLUI.framework/Headers/ -framework OpenGL -framework GLUT -lglui -Wno-deprecated -o lab04
